name: Deploy doc api by gin
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy doc api
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.KEY_ED25519 }}
          passphrase: ${{secrets.PASSPHRASE}}
          script: sh deploy_doc.sh
